# Generated by Django 3.1.5 on 2021-02-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210202_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catergoria',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url_field',
        ),
    ]
